name: Deployment
on: [push]

jobs:
  windows-deploy:
    name: "Windows deploy"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          # yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make --platform win32
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node electron-dev-upload.js --platform=Windows
      
      - name: Send slack notification
        run: |
          node build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Windows

  linux-deploy:
    name: "Linux deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          # yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node electron-dev-upload.js --platform=Linux
      
      - name: Send slack notification
        run: |
          node build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Linux

  macos-deploy:
    name: "MacOS deploy"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          # yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node electron-dev-upload.js --platform=MacOS
      
      - name: Send slack notification
        run: |
          node build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=MacOS
  
        

        

        
