name: Deployment
on: [push]

jobs:
  browser_extension:
    name: "Browser extension deploy"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          # yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make --platform win32
      
      - name: upload Artifacts
        run: |
          node electron-dev-upload.js 
          
      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v1'
      #   # if: runner.os == 'Windows'
      #   # env:
      #   #   CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v1'

      # - name: 'Use gcloud CLI'
      #   run: 'gcloud info'

      # - name: Check files
      #   # if: runner.os == 'Windows'
      #   # env:
      #   #   CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      #   run: |
      #     # ls dist
      #     gsutil ls gs://sk-builds
        
