name: Deployment
on: [push]

jobs:
  browser_extension:
    name: "Browser extension deploy"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # - name: Install dependencies
      #   run: |
      #     git config --global url."https://".insteadOf git://
      #     echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      #     yarn install

      # - name: Build artifacts
      #   run: |
      #     yarn build:web

      - name: 'Gcloud auth'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud
        if: runner.os == 'Windows'
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Check files
        if: runner.os == 'Windows'
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
        run: |
          # ls dist
          gsutil ls gs://poi-dapp
        
