name: Deployment
on: [push]

jobs:
  linux-deploy:
    name: "Linux deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          yarn build:web

      - name: Make windows artifacts
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          yarn make
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node ./scripts/electron-build-upload.js --platform=Linux
      
      - name: Send slack notification
        if: failure()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Linux --failed

      - name: Send slack notification
        if: success()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Linux

      - name: Upload build artifacts (browser extension)
        run: |
          node ./scripts/extension-build-upload.js --platform=BrowserExtension
      
      - name: Send slack notification (browser extension)
        
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=BrowserExtension

  macos-deploy:
    name: "MacOS deploy"
    needs: linux-deploy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node ./scripts/electron-build-upload.js --platform=MacOS

      - name: Send slack notification
        if: failure()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=MacOS --failed

      - name: Send slack notification
        if: success()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=MacOS

  windows-deploy:
    name: "Windows deploy"
    needs: macos-deploy
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          git config --global url."https://".insteadOf git://
          # echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn install

      - name: Build artifacts
        run: |
          yarn build:web

      - name: Make windows artifacts
        run: |
          yarn make --platform win32
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Upload build artifacts
        run: |
          node ./scripts/electron-build-upload.js --platform=Windows
      
      - name: Send slack notification
        if: failure()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Windows --failed

      - name: Send slack notification
        if: success()
        run: |
          node ./scripts/build-notification.js --token=${{ secrets.MATTERMOST_TOKEN }} --platform=Windows

  # ios-deploy:
  #   name: "iOS deploy"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
      
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.12.1'
  #         cache: 'npm'

  # android-deploy:
  #   name: "Android deploy"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
      
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.12.1'
  #         cache: 'npm'