export const appTypes = {
  SET_TEMPLATE : 'kyc/setTemplate',
  KYC_RP_LOAD: 'kyx/rp/load',
	KYC_RP_UPDATE: 'kyc/rp/update',
	KYC_RP_CLEAR: 'kyc/rp/clear',
	KYC_RP_LOAD_FOR_VENDORS: 'kyc/rp/vendors/load',
	KYC_RP_APPLICATION_ADD: 'kyc/rp/application/add',
	KYC_RP_APPLICATION_DELETE: 'kyc/rp/application/delete',
	KYC_RP_APPLICATION_CREATE: 'kyc/rp/application/create',
	KYC_RP_APPLICATION_CANCEL: 'kyc/rp/application/cancel',
	KYC_RP_APPLICATION_UPDATE: 'kyc/rp/application/update',
	KYC_RP_APPLICATION_PAYMENT_UPDATE: 'kyc/rp/application/payment/update',
	KYC_APPLICATION_CURRENT_START: 'kyc/application/current/start',
	KYC_APPLICATION_CURRENT_SET: 'kyc/application/current/set',
	KYC_APPLICATION_CANCEL_ROUTE_SET: 'kyc/application/cancel/route/set',
	KYC_APPLICATION_CURRENT_CLEAR: 'kyc/application/current/clear',
	KYC_APPLICATION_CURRENT_CANCEL: 'kyc/application/current/cancel',
	KYC_APPLICATION_CURRENT_SUBMIT: 'kyc/application/current/submit',
	KYC_APPLICATION_CURRENT_MEMBERS_SUBMIT: 'kyc/application/current/members/submit',
	KYC_RP_MEMBER_APPLICATION_CREATE: 'kyc/applications/current/members/create',
	KYC_APPLICATIONS_LOAD: 'kyc/applications/load',
	KYC_APPLICATIONS_SET: 'kyc/applications/set',
	KYC_APPLICATIONS_UPDATE: 'kyc/applications/update',
	KYC_APPLICATIONS_DELETE: 'kyc/applications/delete',
	KYC_APPLICATIONS_PROCESSING: 'kyc/applications/processing',
	KYC_APPLICATIONS_PROCESSING_SET: 'kyc/applications/set/processing',
	KYC_APPLICATIONS_RESET: 'kyc/applications/reset',
	KYC_APPLICATIONS_REFRESH: 'kyc/applications/refresh',
	KYC_ADD_ADDITIONAL_REQUIREMENTS: 'kyc/applications/requirements/add',
	KYC_UPLOAD_ADDITIONAL_FILES: 'kyc/applications/upload/files',
	KYC_APPLICATION_MESSAGE_SET: 'kyc/application/messages/set',
	KYC_APPLICATION_MESSAGE_CLEAR: 'kyc/application/messages/clear',
	KYC_POST_CHAT_MESSAGE: 'kyc/application/chat/post'
};

export default appTypes;
